let weapons = [
    ["Boomerang",
	false,
	"objects/KoseiHelper/Guns/Bullets/TerrariaBoomerang",
	true,
	"FFFFFF",
	"FFFFFF",
	64,
	"particles/KoseiHelper/star",
	"None",
	"Horizontal",
	0,
	"objects/KoseiHelper/Guns/Bullets/Invisible",
	"event:/KoseiHelper/Guns/shotBoomerang",
	-0.05,
	2000,
	0,
	"None",
	16,
	120,
	0.4,
	0],
	["Crossbow",
	false,
	"objects/KoseiHelper/Guns/TowerFallCrossbow",
	true,
	"e0c9e7",
	"a79aad",
	30,
	"particles/KoseiHelper/star",
	"None",
	"FourDirections",
	0,
	"objects/KoseiHelper/Guns/Bullets/TowerFallArrow",
	"event:/KoseiHelper/Guns/shotArrow",
	-0.01,
	900,
	0.1,
	"VentDust",
	16,
	0,
	0.5,
	0.008],
	["Nemesis",
	true,
	"objects/KoseiHelper/Guns/Bullets/Nemesis",
	true,
	"4682b4",
	"ffff00",
	12,
	"particles/KoseiHelper/star",
	"ReplacesDash",
	"Horizontal",
	0,
	"objects/KoseiHelper/Guns/NemesisGun",
	"event:/KoseiHelper/Guns/shotDefault",
	0,
	350,
	0.25,
	"Normal",
	0,
	0,
	0.7,
	0],
	["Meowgun",
	false,
	"objects/KoseiHelper/Guns/Bullets/TerrariaMeow",
	true,
	"e716a0",
	"4312e6",
	9,
	"particles/KoseiHelper/star",
	"None",
	"EightDirections",
	0,
	"objects/KoseiHelper/Guns/Meowgun",
	"event:/KoseiHelper/Guns/shotMeow",
	0,
	650,
	1,
	"Ice",
	0,
	0,
	0.9,
	0],
	["Firework",
	true,
	"objects/KoseiHelper/Guns/Bullets/Invisible",
	true,
	"eb6e14",
	"e7b915",
	12,
	"particles/KoseiHelper/star",
	"None",
	"FourDirections",
	3,
	"objects/KoseiHelper/Guns/Firework",
	"event:/KoseiHelper/Guns/shotFirework",
	0.05,
	1800,
	1,
	"Fire",
	20,
	200,
	0.1,
	-0.015],
	["Löve",
	true,
	"objects/KoseiHelper/Guns/Bullets/Heart",
	true,
	"e95cec",
	"cd3784",
	8,
	"particles/KoseiHelper/star",
	"ConsumesDash",
	"EightDirections",
	2,
	"objects/KoseiHelper/Guns/Bullets/Heart",
	"event:/KoseiHelper/bulletB",
	-0.01,
	3600,
	0.35,
	"Custom",
	12,
	80,
	0.22,
	0.007],
	["Bomb Launcher"]
];

function getLauncher(name) {
    return `{
    {
        _editorLayer = 0,
        _fromLayer = "entities",
        _id = 1,
        _name = "KoseiHelper/SpawnController",
        absoluteCoords = false,
        appearSound = "event:/none",
        blockHeight = 16,
        blockSinks = false,
        blockTileType = "3",
        blockWidth = 16,
        boosterRed = false,
        cloudFragile = true,
        crushBlockAxe = "Both",
        crushBlockChillout = false,
        dashBlockCanDash = true,
        decalDepth = 9000,
        decalTexture = "10-farewell/creature_f00",
        decreaseCounter = false,
        dictKeys = "explodeOnSpawn,explodeTime,respawnOnExplode",
        dictValues = "true,0.3,false",
        disappearSound = "event:/none",
        dummyFix = true,
        entityPath = "Celeste.Mod.CavernHelper.CrystalBomb",
        entityToSpawn = "CustomEntity",
        everyXDashes = 1,
        fallingBlockBadeline = false,
        fallingBlockClimbFall = false,
        featherShielded = false,
        featherSingleUse = true,
        flag = "",
        flagCycleAt = 9999,
        flagStop = false,
        flagValue = true,
        iceballAlwaysIce = false,
        iceballSpeed = 1,
        jumpthruTexture = "wood",
        maxCounterCap = 9999,
        minCounterCap = 0,
        moveBlockCanSteer = false,
        moveBlockDirection = "Down",
        moveBlockFast = true,
        nodeRelativeToPlayerFacing = true,
        nodeX = 0,
        nodeY = 0,
        offsetX = 0,
        offsetY = 0,
        persistent = false,
        poofWhenDisappearing = false,
        refillTwoDashes = false,
        relativeToPlayerFacing = true,
        removeDash = false,
        removeStamina = false,
        soundIndex = -1,
        spawnCondition = "OnFlagEnabled",
        spawnCooldown = 0,
        spawnFlag = "KoseiHelper_playerIsShooting",
        spawnFlagValue = true,
        spawnLimit = -1,
        spawnSpeed = 300,
        swapBlockTheme = "Normal",
        timeToLive = 5,
        x = 704,
        y = 48,
        zipMoverTheme = "Normal"
    },
    {
        _editorLayer = 0,
        _fromLayer = "entities",
        _id = 2,
        _name = "KoseiHelper/SpawnController",
        absoluteCoords = false,
        appearSound = "event:/none",
        blockHeight = 16,
        blockSinks = false,
        blockTileType = "3",
        blockWidth = 16,
        boosterRed = false,
        cloudFragile = true,
        crushBlockAxe = "Both",
        crushBlockChillout = false,
        dashBlockCanDash = true,
        decalDepth = 9000,
        decalTexture = "10-farewell/creature_f00",
        decreaseCounter = false,
        dictKeys = "whitelist,attachTo,ignoreAnchors,ignoreContainerBounds,destroyable,fitContained,restrictToNode",
        dictValues = "CrystalBomb,Bullet,true,true,false,true,false",
        disappearSound = "event:/none",
        dummyFix = true,
        entityPath = "Celeste.Mod.EeveeHelper.Entities.AttachedContainer",
        entityToSpawn = "CustomEntity",
        everyXDashes = 1,
        fallingBlockBadeline = false,
        fallingBlockClimbFall = false,
        featherShielded = false,
        featherSingleUse = true,
        flag = "",
        flagCycleAt = 9999,
        flagStop = false,
        flagValue = true,
        iceballAlwaysIce = false,
        iceballSpeed = 1,
        jumpthruTexture = "wood",
        maxCounterCap = 9999,
        minCounterCap = 0,
        moveBlockCanSteer = false,
        moveBlockDirection = "Down",
        moveBlockFast = true,
        nodeRelativeToPlayerFacing = true,
        nodeX = 0,
        nodeY = 0,
        offsetX = 24,
        offsetY = 0,
        persistent = false,
        poofWhenDisappearing = false,
        refillTwoDashes = false,
        relativeToPlayerFacing = true,
        removeDash = false,
        removeStamina = false,
        soundIndex = -1,
        spawnCondition = "OnFlagEnabled",
        spawnCooldown = 0,
        spawnFlag = "KoseiHelper_playerIsShooting",
        spawnFlagValue = true,
        spawnLimit = -1,
        spawnSpeed = 300,
        swapBlockTheme = "Normal",
        timeToLive = 5,
        x = 672,
        y = 48,
        zipMoverTheme = "Normal"
    },
    {
        _editorColor = "",
        _editorLayer = 0,
        _fromLayer = "triggers",
        _id = 3,
        _name = "KoseiHelper/NemesisGunSettings",
        bulletExplosion = false,
        bulletTexture = "objects/KoseiHelper/Guns/Bullets/Invisible",
        canShootInFeather = false,
        color1 = "78acfb",
        color2 = "262070",
        cooldown = 40,
        customParticleTexture = "particles/KoseiHelper/star",
        dashBehavior = "None",
        directions = "EightDirections",
        enabled = true,
        freezeFrames = 0,
        gunTexture = "objects/KoseiHelper/Guns/Bullets/Invisible",
        gunshotSound = "event:/KoseiHelper/bullet",
        height = 64,
        horizontalAcceleration = 0,
        lifetime = 600,
        loseGunOnRespawn = false,
        particleAlpha = 0.08,
        particleType = "Bubble",
        recoilCooldown = 0,
        recoilStrength = 0,
        speedMultiplier = 0.28,
        triggerMode = "OnStay",
        verticalAcceleration = 0,
        width = 64,
        x = 656,
        y = 32
    }
}`;
}

function getEntity(name, bulletExplosion, bulletTexture, canShootInFeather, color1, color2, cooldown, customParticleTexture, dashBehavior, directions, freezeFrames,
gunTexture, gunshotSound, horizontalAcceleration, lifetime, particleAlpha, particleType, recoilCooldown, recoilStrength, speedMultiplier, verticalAcceleration) {
    return `{
    {
        _fromLayer = "triggers",
        _name = "KoseiHelper/NemesisGunSettings",
        bulletExplosion = ${bulletExplosion},
        bulletTexture = "${bulletTexture}",
        canShootInFeather = ${canShootInFeather},
        color1 = "${color1}",
        color2 = "${color2}",
        cooldown = "${cooldown}",
        customParticleTexture = "${customParticleTexture}",
        dashBehavior = "${dashBehavior}",
        directions = "${directions}",
        enabled = true,
        freezeFrames = "${freezeFrames}",
        gunTexture = "${gunTexture}",
        gunshotSound = "${gunshotSound}",
        height = 64,
        horizontalAcceleration = "${horizontalAcceleration}",
        lifetime = "${lifetime}",
        loseGunOnRespawn = false,
        particleAlpha = "${particleAlpha}",
        particleType = "${particleType}",
        recoilCooldown = "${recoilCooldown}",
        recoilStrength = "${recoilStrength}",
        speedMultiplier = "${speedMultiplier}",
        triggerMode = "OnStay",
        verticalAcceleration = "${verticalAcceleration}",
        width = 64,
        x = 0,
        y = 0
    }
}`;
}



function buttonClick(button) {
    let index = button.id.substring(7);
    let info = weapons[index];
    if (index == 6) {
        navigator.clipboard.writeText(getLauncher(...info)); 
    } else {
        navigator.clipboard.writeText(getEntity(...info)); 
    }
    button.innerHTML = "Copied!";
    button.style.backgroundColor = "#e1bde0";
    setDefaultColor(button);
}


async function setDefaultColor(button) {
    await sleep(1000);
    button.innerHTML = "Copy";
    button.style.backgroundColor = null;
}

function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}

for (let i = 0; i < weapons.length; i++) {
    let info = weapons[i];

    let e = document.createElement("DIV");
    
    let br = document.createElement("BR");

    let title = document.createElement("H2");
    title.innerHTML = info[0];

    let image = document.createElement("IMG");
    image.setAttribute("src", "./Images/weapons/" + info[0] + ".png");

    let button = document.createElement("BUTTON");
    button.innerHTML = "Copy";
    button.id = "button_" + i;
    button.setAttribute("onclick", "buttonClick(this)");

    e.append(title);
    e.append(image);
    e.append(br);
    e.append(button);

    document.body.append(e);
}
